#!/bin/bash

function setup {
    pip install -r requirements.txt
    pip install --pre torch==2.6.0.dev20241203+cu124 --index-url https://download.pytorch.org/whl/nightly/cu124 --upgrade
    python data/cached_fineweb10B.py 10
}

function run {
    torchrun --standalone --nproc_per_node=1 train_gpt2.py
}

function docker {
    sudo docker build -t modded-nanogpt .
    sudo docker run -it --rm --gpus all -v $(pwd):/modded-nanogpt modded-nanogpt bash
}