#!/bin/bash
# https://github.com/akriegman/run

function setup {
    pip install -r requirements.txt
    pip install --pre torch==2.6.0.dev20241231+cu126 --index-url https://download.pytorch.org/whl/nightly/cu126 --upgrade
    python data/cached_fineweb10B.py 8
}

function run {
    torchrun --standalone --nproc_per_node=1 train_gpt.py
}
